### ISSUE TITLE
won't be connected !!

### ISSUE THREAD

**Issue by SAV-404** [Agarian/agarian.github.io#1]
![capture](https://user-images.githubusercontent.com/26459304/31862650-4e3f58ea-b739-11e7-97fa-12f2424302c7.PNG)
and of course i'm running my server in port 443.

**Comment by AlexHGaming** [comment]
@SAV-404 what are you hosting your website on?

**Comment by SAV-404** [comment]
nooh...i used this link : https://agarian.github.io/agarian.github.io/

**Comment by SAV-404** [comment]
i fixed it now ..i downloaded the project then i used XAMPP to play on it in my localhost...thanks anyway !!
