### ISSUE TITLE
How To Add zoom in/out to your client ?

### ISSUE THREAD

**Issue by AhmedAliWT** [Agarian/agarian.github.io#10]
Hello , Thanks for your nice web client 
Please, If you can help me how can I add zoom out to this client ? 
thanks for your help
waiting for your reply

**Comment by Agarian** [comment]
But it already exists...?

**Comment by AhmedAliWT** [comment]
I can't find that :( I'm using my mouse wheel but I can't zoom out too much with that ,  It's limited
I'm speaking about "ultra zoom" as they are called
thanks for your reply

**Comment by Agarian** [comment]
Oh, I see what you mean. It's relatively easy to add, but I didn't add it because I didn't want to. You should read #9 to know why.

**Comment by AhmedAliWT** [comment]
So you cant help me only with code ?
Ok bro I'm sorry for wasting you time
And thank you
بتاريخ ١٨‏/٠١‏/٢٠١٨ ٨:٠٤ م، كتب "Tom" <notifications@github.com>:

**Comment by Agarian** [comment]
No, no, I can, I just don't have the time right now.

**Comment by AhmedAliWT** [comment]
okay, thanks Tom for your reply

**Comment by AhmedAliWT** [comment]
@Agarian , I'm sorry Tom again , but really I want the code unlimited zoom out too much , I'm searching for that about 15days to now and I can't find that , please you are my last chance for that If you can help me with the code I will be thankful for you .
I'm sorry for noise and thanks for your help <3

**Comment by RevengePlayz** [comment]
@Agarian Please add me on discord Revenge#5285 please i need help really bad, and im sure you could help asap thanks

**Comment by Agarian** [comment]
@RevengePlayz @egyahmedali 
Alright, to get infinite zoom remove the following line from `main_out.js`:
https://github.com/Agarian/agarian.github.io/blob/master/assets/js/main_out.js#L422

**Comment by Agarian** [comment]
Closing this since it has been resolved. Also, do note that I will be adding a checkbox option for infinite zoom.
