### ISSUE TITLE
I NEED HELP!!!

### ISSUE THREAD

**Issue by RevengePlayz** [Agarian/agarian.github.io#11]
@Agarian Please add me on discord, im experiencing alot of issues.I think you might be able to help me with i appriciate if you add me on discord and talk to me about the problems im having troubles with.
Discord:Revenge#5285 (make sure its a capital R)

**Comment by Agarian** [comment]
LIKE I SAID IN #3 @RevengePlayz Just join https://discord.gg/TJpz8a and PM me from there.

**Comment by Agarian** [comment]
Resolved.
