### ISSUE TITLE
Some of the skins don't render.

### ISSUE THREAD

**Issue by random-player** [Agarian/agarian.github.io#17]
When I added my own skins, it doesn't wanna render. I use the name "beno" which is a skin name, but doesn't render it. This is the skin for the name "beno":
![beno](https://user-images.githubusercontent.com/26576570/40934824-b9541934-683e-11e8-81d5-162a992da9af.png)

But gives me this in the game: 
![ekran goruntusu 241](https://user-images.githubusercontent.com/26576570/40934842-c732a4f8-683e-11e8-9b2b-79fd3987724e.png)

I need some help for this!

**Comment by Seriously0000** [comment]
I used my modified version of MultiOgar. The version is 1.3.6-b3. b3 standing for build 3.  But it supports skins. So why it doesn't work is stupid. My other client DOES render.
