### ISSUE TITLE
which one exactly??

### ISSUE THREAD

**Issue by SAV-404** [Agarian/agarian.github.io#18]
which part renders the cell's **_split_** and its **_moving_** **_speed_** ?

_thank you !_
@Agarian

**Comment by Agarian** [comment]
The moving speed is a server-side event, though I've abandoned this client long ago, so I'm unsure about where splitting is rendered lol

**Comment by SAV-404** [comment]
i meant by saying moving speed, the speed how the cell follows the mouse, you know, every time u move the mouse from side to side the cell follows it in a certain speed, so i don't think this is a server-side event.
and please check the code really quickly, plz :")))) ???
**in french:** _s'il vous plait??_

**Comment by SAV-404** [comment]
i'm on it
