### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by AlexHGaming** [Agarian/agarian.github.io#2]
I fired up a port 443 server on my PC, tried connecting to port 443 server and the following message in Inspect Element occurs:
WebSocket connection to 'wss://127.0.0.1/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
WrappedWebSocket @ VM143:161
wsConnect @ main_out.js:503
showConnecting @ main_out.js:481
main_out.js:532 Socket closed

**Comment by AlexHGaming** [comment]
This is maybe due to hosting on github.

**Comment by Agarian** [comment]
Yes, it is. There's no way around it, unfortunately (besides downloading it).
