### ISSUE TITLE
(Spanish) Cambiar el leaderboard

### ISSUE THREAD

**Issue by mafiakb** [Agarian/agarian.github.io#4]
Agaria como puedo cambiar el leaderboard osea que algo asi:

```<div id="leader">
  <div id="nameLeader">Leaderboard</div>
  <p>
     <li>User1</li>
     <li>User2</li>
     <li>User2</li>
  </p>
</div>
```

Hay alguna forma? para poder modificar en tu cliente :/

**Comment by Agarian** [comment]
@mafiakb Si bien podría hacerlo a través del cliente, creo que sería mucho más fácil editar eso en el lado del servidor. Y solo una pregunta, ¿quiere que el texto de la tabla de clasificación muestre específicamente "Usuario" y luego un número anterior? **Nota al margen:** la edición de la tabla de clasificación no funcionará en HTML. Y lo siento si mi gramática española es mala, culpen a Google traducir y mi pobre conocimiento de español.

**Comment by mafiakb** [comment]
Claro, seria en el lado del cliente. La idea es que se cada usuario en el leaderboard tenga ```<li>user1</li> ```para poder darle ediciones en un futuro.

**Comment by Agarian** [comment]
De la forma en que lo veo, tendrás que cambiar el siguiente código **de:** 
```js
 for (ctx.font = "20px Ubuntu", b = 0; b < leaderBoard.length; ++b) {
    c = leaderBoard[b].name || "An unnamed cell";
    if (!showName) c = "An unnamed cell";
    if (-1 != nodesOnScreen.indexOf(leaderBoard[b].id)) {
        playerCells[0].name && (c = playerCells[0].name);
        var userLBColor = String($("#lbColor").val());
        ctx.fillStyle = "#" + userLBColor;
        if (!noRanking) c = b + 1 + ". " + c;
        ctx.fillText(c, 100 - ctx.measureText(c).width / 2, 70 + 24 * b);
    } else {
        ctx.fillStyle = "#FFF";
        if (!noRanking) c = b + 1 + ". " + c;
        ctx.fillText(c, 100 - ctx.measureText(c).width / 2, 70 + 24 * b);
    }
}
```
**A:**
```js
for (ctx.font = "20px Ubuntu", b = 0; b < leaderBoard.length; ++b) {
    c = leaderBoard[b].name || "User";
    if (!showName) c = "User";
    if (-1 != nodesOnScreen.indexOf(leaderBoard[b].id)) {
        playerCells[0].name && (c = playerCells[0].name);
        var userLBColor = String($("#lbColor").val());
        ctx.fillStyle = "#" + userLBColor;
        if (!noRanking) c = b + 1 + ". " + c;
        ctx.fillText("User", 100 - ctx.measureText("User").width / 2, 70 + 24 * b);
    } else {
        ctx.fillStyle = "#FFF";
        if (!noRanking) c = b + 1 + ". " + c;
        ctx.fillText("User", 100 - ctx.measureText("User").width / 2, 70 + 24 * b);
    }
}
```
Este código se encuentra en:
https://github.com/Agarian/agarian.github.io/blob/master/assets/js/main_out.js#L1058

**Comment by Agarian** [comment]
@mafiakb Lo que este cambio efectivamente hace es hacer que todos los nombres en la pantalla de la tabla de clasificación sean "Usuario". En cuanto a los números anteriores después del texto, como 1, 2, 3, 4 ..., esta es la razón por la que sugerí editar el código del servidor para esta función, ya que no hay forma de que sepa agregar los números anteriores en el cliente.

**Comment by mafiakb** [comment]
@Agarian Claro solo creo que me entendiste mal digamos yo en el cliente html tengo esto:

```<div id="leaderboard-wrapper" style="display: block;">
          <div id="leaderboard-content-wrapper">
            <span id="leaderboard-header">Leaderboard</span>
            <li></li>
          </div>
        </div>
```
Lo que quiero que se emprima son los nicks en la etiqueta ```<li></li> ``` esta funcion:

```
if (!noRanking) c = b + 1 + ". " + c;
```
algo asi seria $("#leaderboard-header .li").html(c); pero no funciona solo muestra el primer nick no muestra todos.
 
Tiene que mostrar asi todos los nicks.
```
<div id="leaderboard-wrapper" style="display: block;">
          <div id="leaderboard-content-wrapper">
            <span id="leaderboard-header">Leaderboard</span>
              <li>agarian</li>
              <li>mafiakb</li>
              <li>agarian</li>
              <li>mafiakb</li>
              <li>agarian</li>
              <li>mafiakb</li>
              <li>agarian</li>
              <li>mafiakb</li>
          </div>
        </div>

```

**Comment by Agarian** [comment]
@mafiakb Oh, está bien, veo lo que quieres. Dame algo de tiempo para ver si puedo hacer que funcione. Aunque no estoy seguro de cómo funcionará, intentaré hacerlo lo mejor posible.

**Comment by Agarian** [comment]
Seré honesto contigo, no estoy seguro por dónde empezar con esto. Pero gracias por señalar:
 `if (!noRanking) c = b + 1 + ". " + c;`. Ese código lo hace un poco más fácil. Esto es lo que tengo hasta ahora, he conseguido que la tabla de clasificación muestre `Usuario` luego un número anterior. El código para eso está abajo.
```js
for (ctx.font = "20px Ubuntu", b = 0; b < leaderBoard.length; ++b) {
    c = leaderBoard[b].name || "An unnamed cell";
    if (!showName) c = "An unnamed cell";
    if (-1 != nodesOnScreen.indexOf(leaderBoard[b].id)) {
        playerCells[0].name && (c = playerCells[0].name);
        var userLBColor = String($("#lbColor").val());
        ctx.fillStyle = "#" + userLBColor;
        if (!noRanking) c = b + 1 + ". " + "User " + b;
        ctx.fillText(c, 100 - ctx.measureText(c).width / 2, 70 + 24 * b);
    } else {
        ctx.fillStyle = "#FFF";
        if (!noRanking) c = b + 1 + ". " + "User " + b;
        ctx.fillText(c, 100 - ctx.measureText(c).width / 2, 70 + 24 * b);
    }
}
```

**Comment by mafiakb** [comment]
@Agarian ok buscare mas afondo para lograr y poner avances aqui.

**Comment by RevengePlayz** [comment]
@mafiakb and @Agarian add me on discord Revenge#5285 its urgent (do capital R)

**Comment by Agarian** [comment]
Closing this.
