### ISSUE TITLE
(Spanish) Como se agrega party?

### ISSUE THREAD

**Issue by mafiakb** [Agarian/agarian.github.io#6]
Como podria agregar el modo party al cliente ?

**Comment by mafiakb** [comment]
@Agarian sabes como se puede implementar?

**Comment by Agarian** [comment]
Sorry to say, but no. I mean there is a `Cell Border Color` option in the options section, but that will change the color of all cell borders. So if you want a yellow outline on cells, change that option from `000000` to `FFFF00`.

**Comment by Agarian** [comment]
@mafiakb Perdón por decirlo, pero no. Quiero decir que hay una opción de `Color del borde` (Cell Border Color) de la celda en la sección de opciones, pero eso cambiará el color de todos los bordes de la celda. Entonces, si desea un contorno amarillo en las celdas, cambie esa opción de `000000` a `FFFF00`.

**Comment by mafiakb** [comment]
@Agarian no me refiero a los bordes de los colores me refiero para agregar party friend a para tipo agar.io

**Comment by Agarian** [comment]
Eso es lo que estoy diciendo. No sabría cómo agregar tal sistema.

**Comment by Agarian** [comment]
Closing this.
