### ISSUE TITLE
(spanish) como agregar hats?

### ISSUE THREAD

**Issue by mafiakb** [Agarian/agarian.github.io#8]
Puedes darme una idea de como agregar hats a la seccion skins?

**Comment by mafiakb** [comment]
@Agarian alguna idea?

**Comment by Agarian** [comment]
¿Estás hablando simplemente de agregar máscaras al cliente o agregar sombreros literales que aparecen encima de la celda? Perdón por la respuesta tardía = /

**Comment by mafiakb** [comment]
@Agarian sobreros que aparescan encima de la celda.
  
![image](https://user-images.githubusercontent.com/12769609/34750679-5aa1e9f6-f576-11e7-92aa-abc697d317c3.png)

**Comment by RevengePlayz** [comment]
@mafiakb add me on discord Revenge#5285 its urgent please

**Comment by Agarian** [comment]
You mind **not** spamming the issues? I already helped you!

**Comment by Agarian** [comment]
@mafiakb Sí, no tengo ni idea de cómo agregar eso (sin dividir al cliente). Me estoy volviendo estúpido, considerando que estoy seguro de que así es como he respondido en casi todos tus problemas. De cualquier manera, no sé cómo agregar esto, no me molestaré en averiguarlo, porque como he mencionado, hice esto solo para mis propósitos. Entonces, si a alguien no le gusta la forma en que está, lástima. Lo siento si me sale grosero o algo así, pero soy flojo :P

I'm going to close this...
